version: 2

language: en

build:
  os: ubuntu-20.04 
  tools:
    python: "3.10"  
    sphinx: "4.5.0"  
  commands:
    - make html 

sphinx:
  configuration: docs/source/conf.py 

python:
  version: "3.10"  
  install:
    - requirements: docs/requirements.txt 
