version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.13"

python:
  install:
    - requirements: docs/requirements.txt
  commands:
    - pip install requirements.txt

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: ./source/conf.py
