version: 2

# Language of the documentation
language: en

# Specify the build environment
build:
  os: ubuntu-20.04  # Valid values: ubuntu-20.04, ubuntu-18.04
  tools:
    sphinx: "4.5.0"  # Specify the Sphinx version you are using
  commands:
    - make html  # Build the documentation


# Define the Sphinx configuration
sphinx:
  configuration: docs/conf.py  # Path to your Sphinx config file

# Python configuration
python:
  version: "3.9"  # Specify the Python version
  install:
    - requirements: docs/requirements.txt  # Path to your requirements file
